### ISSUE TITLE
Synchronization Error

### ISSUE THREAD

**Issue by Clark-Whitehead** [Clark-Whitehead/asklana#6]
In this file - https://github.com/Clark-Whitehead/asklana/blob/main/src/features/chat/textBox/TextBox.js

I'm trying to update chat using dispatch(addHuman(text)); which works, but not in time enough apparently to be used in the line: axios.post('http://localhost:4001/apiTest', {message: chat + "\n\n" + "Human: " + temp + "\n\nLana:"})

I'd prefer it be something like this axios.post('http://localhost:4001/apiTest', {message: chat})

Please submit a pull request if you figure it out. Thanks

**Comment by Clark-Whitehead** [comment]
Ended up going with store.getState().chat

I wish chat would just update on it's own.

**Comment by mpaccione** [comment]
If you dockerize the application I can assist. 
You would want to organize the code so that your api calls are not in the same component. They would typically go into an actions folder/index file.

You would typically useSelector and pass the id into the dispatch.
However getState is passed automatically into actions. 
Once again reference either of these repos as examples.

https://github.com/mpaccione/full-stack-todo-2022
https://github.com/mpaccione/full-stack-vending-machine-2022

```js
const handleClick = async () => {

        if (text.length > 0) {
            await dispatch(addHuman(text));
            setText("");

           // abstract this out into an actions file and use a base axios instance for brevity
           // example was in the code repo I had sent you earlier
          try {  
            const res = await axios.post('http://localhost:4001/apiTest', {message: store.getState().chat.chat})
            if (res.status === 200) {
                dispatch(addAi(res.data.responseOut));
                dispatch(addResponse({id: store.getState().chat.id, chat: store.getState().chat.chat}));
                convo.scrollTop = convo.scrollHeight;
            }
         } catch (err) {
            console.log(err)
        }
    }
```
